"use strict";
// =========================================================================
// QUIZ DATA — Erhvervsøkonomi (semester 3)
//
// Every question is paraphrased from an actually-inspected source: either
// subjects/semester-3/erhvervsoekonomi/notes/*.md (an OneNote-derived note,
// cited via sourceLabel) or the flowplan's own learning-goal wording. See
// tools/studieoverblik/QUIZ-ARCHITECTURE.md for the full source mapping,
// including documented gaps (places the notes flag as unread/unconfirmed,
// which are deliberately NOT turned into graded fact questions here).
//
// difficulty: 1 = basis/genkendelse, 2 = forståelse/enkel anvendelse,
// 3 = analyse/beregning/modelvalg, 4 = kompleks case/sammenligning.
// questionVersion bumps only if a question's factual content changes later.
// =========================================================================
const quizBanksEO = {

  // ======================================================================
  // UGE 34a — Virksomhedens årsregnskab & bogføringssystem
  // Sources: virksomhedens-aarsregnskab-og-bogfoering.md, bogfoeringssystemet.md,
  // debet-kredit-oversigt.md
  // ======================================================================
  uge34a: {
    basis: [
      { id:"u34a-b1", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"mc", difficulty:1, tags:["bogfoering"], prompt:"Hvordan påvirkes en omkostningskonto normalt, når omkostningen stiger?", options:["Den krediteres","Den debiteres","Den påvirkes ikke","Den lukkes direkte mod egenkapitalen"], correct:1, explanation:"Omkostninger øges i debet og mindskes i kredit.", questionVersion:1 },
      { id:"u34a-b2", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"mc", difficulty:1, tags:["bogfoering"], prompt:"Hvordan påvirkes en indtægtskonto normalt, når indtægten stiger?", options:["Den debiteres","Den krediteres","Den flyttes til aktiver","Den påvirkes ikke"], correct:1, explanation:"Indtægter øges i kredit og mindskes i debet.", questionVersion:1 },
      { id:"u34a-b3", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"tf", difficulty:1, tags:["bogfoering"], prompt:"Aktiver som varebeholdning, kundefordringer og bank øges i debet.", correct:true, explanation:"Aktivkonti har debetsaldo: de øges i debet og mindskes i kredit.", questionVersion:1 },
      { id:"u34a-b4", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"tf", difficulty:1, tags:["bogfoering"], prompt:"Leverandørgæld og banklån øges i debet.", correct:false, explanation:"Gæld er en passivpost og øges derfor i kredit; den mindskes i debet.", questionVersion:1 },
      { id:"u34a-b5", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"match", difficulty:2, tags:["bogfoering"], prompt:"Match kontotype og den side, hvor kontoen øges.", terms:["Omkostning","Indtægt","Aktiv","Passiv"], defs:["Debet","Kredit","Debet","Kredit"], explanation:"Omkostninger og aktiver øges i debet. Indtægter, egenkapital og gæld øges i kredit.", questionVersion:1 },
      { id:"u34a-b6", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"flash", difficulty:1, tags:["bogfoering"], prompt:"Huskeregel: Hvilke hovedgrupper har normalt debetsaldo?", back:"Omkostninger og aktiver.", questionVersion:1 },
      { id:"u34a-b7", goalId:"uge34a-g1", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Virksomhedens årsregnskab og bogføring (Uge 34.1)", type:"mc", difficulty:1, tags:["aarsrapport"], prompt:"Hvad viser resultatopgørelsen?", options:["Aktiver og passiver på et bestemt tidspunkt","Indtægter minus omkostninger for perioden","Virksomhedens likvide beholdning ved årets start","Kun virksomhedens gæld"], correct:1, explanation:"Resultatopgørelsen viser periodens driftsaktiviteter: indtægter minus omkostninger giver over- eller underskud.", questionVersion:1 },
      { id:"u34a-b8", goalId:"uge34a-g1", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Virksomhedens årsregnskab og bogføring (Uge 34.1)", type:"mc", difficulty:1, tags:["aarsrapport"], prompt:"Hvad viser balancen, som resultatopgørelsen ikke gør?", options:["Periodens overskud","Et øjebliksbillede af aktiver og passiver på balancetidspunktet","Kun periodens omsætning","Virksomhedens kundetilfredshed"], correct:1, explanation:"Balancen giver et øjebliksbillede af aktiver og passiver, i modsætning til resultatopgørelsen, der viser resultatet over en periode.", questionVersion:1 },
      { id:"u34a-b9", goalId:"uge34a-g1", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Virksomhedens årsregnskab og bogføring (Uge 34.1)", type:"tf", difficulty:2, tags:["aarsrapport","fejlslutning"], prompt:"En indtægt og en indbetaling registreres altid på samme dato.", correct:false, explanation:"En indtægt registreres, når varen/ydelsen er solgt (leveringstidspunktet), mens en indbetaling først registreres, når pengene rent faktisk modtages — de to kan falde i hvert sit regnskabsår.", questionVersion:1 },
      { id:"u34a-b10", goalId:"uge34a-g1", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Virksomhedens årsregnskab og bogføring (Uge 34.1)", type:"mc", difficulty:1, tags:["aarsrapport"], prompt:"Hvad kendetegner en variabel omkostning?", options:["Den er uafhængig af salget","Den ændrer sig direkte med den solgte mængde","Den optræder kun i balancen","Den er altid en afskrivning"], correct:1, explanation:"Variable omkostninger ændrer sig direkte med den solgte mængde, fx vareforbrug — i modsætning til faste omkostninger som husleje.", questionVersion:1 },
      { id:"u34a-b11", goalId:"uge34a-g1", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Virksomhedens årsregnskab og bogføring (Uge 34.1)", type:"mc", difficulty:1, tags:["aarsrapport"], prompt:"Hvad er aktiver, ifølge balancens grundopdeling?", options:["Kapitalfremskaffelse","Kapitalanvendelse","Kun kontanter","Virksomhedens overskud"], correct:1, explanation:"Aktiver er kapitalanvendelse — hvad pengene er brugt på (anlæg, varelager, tilgodehavender, kontanter). Passiver er kapitalfremskaffelse.", questionVersion:1 },
      { id:"u34a-b12", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:1, tags:["bogfoering","regnskabsidentitet"], prompt:"Hvad udtrykker regnskabsidentiteten?", options:["Egenkapital = gæld", "Aktiver = passiver", "Omsætning = omkostninger", "Debet = indtægt"], correct:1, explanation:"Regnskabsidentiteten er aktiver = passiver: anlægsaktiver + omsætningsaktiver = egenkapital + fremmedkapital. Balancens to sider skal altid være lige store.", questionVersion:1 },
      { id:"u34a-b13", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"tf", difficulty:2, tags:["bogfoering"], prompt:"En ombytning, fx afdrag på et banklån, ændrer virksomhedens egenkapital.", correct:false, explanation:"Ved en ombytning byttes blot ét aktiv/passiv for et andet (banken falder, gælden falder lige så meget) — egenkapitalen er uændret. Kun resultatpåvirkende posteringer (omkostninger/indtægter) ændrer egenkapitalen.", questionVersion:1 },
      { id:"u34a-b14", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:1, tags:["moms"], prompt:"Fra hvilken årlig omsætning skal en virksomhed momsregistreres?", options:["10.000 kr.","50.000 kr.","100.000 kr.","500.000 kr."], correct:1, explanation:"Virksomheder med en årlig omsætning over 50.000 kr. skal momsregistreres og afregne 25 % moms af værditilvæksten.", questionVersion:1 },
      { id:"u34a-b15", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"tf", difficulty:2, tags:["moms","fejlslutning"], prompt:"En privat forbruger kan fratrække momsen på sine indkøb, ligesom en momsregistreret virksomhed kan.", correct:false, explanation:"Private forbrugere kan ikke få momsen refunderet — den er en endelig omkostning for dem. En momsregistreret køber kan derimod fratrække momsen som sin egen købsmoms.", questionVersion:1 },
    ],
    anvendelse: [
      { id:"u34a-a1", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"mc", difficulty:2, tags:["bogfoering"], scenario:"Virksomheden køber varer på kredit. Varebeholdningen og leverandørgælden stiger.", prompt:"Hvilken kombination følger oversigten?", options:["Varebeholdning kredit; leverandørgæld debet","Varebeholdning debet; leverandørgæld kredit","Begge debet","Begge kredit"], correct:1, explanation:"Varebeholdning er et aktiv og øges i debet. Leverandørgæld er et passiv og øges i kredit.", questionVersion:1 },
      { id:"u34a-a2", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"mc", difficulty:2, tags:["bogfoering"], scenario:"En kunde betaler kontant for en vare, så bankbeholdningen og salgsindtægten stiger.", prompt:"Hvordan øges de to konti?", options:["Bank i debet og salgsindtægt i kredit","Bank i kredit og salgsindtægt i debet","Begge i debet","Begge i kredit"], correct:0, explanation:"Bank er et aktiv og øges i debet; salgsindtægten øges i kredit.", questionVersion:1 },
      { id:"u34a-a3", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Debet/kredit-oversigt", type:"self", difficulty:3, tags:["bogfoering","case"], prompt:"Lav selv tre posteringer: én omkostning, én indtægt og én balancepost. Forklar for hver, hvorfor kontoen går i debet eller kredit.", checklist:["Klassificerer kontoen korrekt","Bruger reglen om, hvor kontotypen øges og mindskes","Forklarer begge sider af hver postering"], questionVersion:1 },
      { id:"u34a-a4", goalId:"uge34a-g1", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Virksomhedens årsregnskab og bogføring (Uge 34.1)", type:"self", difficulty:3, tags:["aarsrapport","case"], scenario:"Et snedkerfirma sender en faktura for et udført stykke arbejde d. 20. december, med betalingsfrist 30 dage.", prompt:"Forklar, hvornår beløbet er en indtægt, og hvornår det er en indbetaling — og hvorfor det kan betyde, at de to poster ryger i hvert sit regnskabsår.", checklist:["Indtægten bogføres i december, hvor arbejdet er udført/faktureret","Indbetalingen bogføres først, når kunden rent faktisk betaler (januar)","Forklarer konsekvensen: et tilgodehavende (debitor) opstår i balancen indtil betaling"], questionVersion:1 },
      { id:"u34a-a5", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:3, tags:["bogfoering","beregning"], scenario:"En virksomhed med primobalance 425 gennemfører en række transaktioner. Bruttofortjenesten ender på 95 (varesalg 150 − vareforbrug 55), og der er andre omkostninger på 6 samt afskrivninger på 60.", prompt:"Hvad bliver årets resultat?", options:["29","95","150","89"], correct:0, explanation:"Årets resultat = bruttofortjeneste 95 − andre omkostninger 6 − afskrivninger 60 = 29.", questionVersion:1 },
      { id:"u34a-a6", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"self", difficulty:4, tags:["bogfoering","fejlslutning"], scenario:"En medstuderende siger: \"Et varesalg på kredit ødelægger jo balancen — kun tilgodehavendet (aktivet) stiger, der er ikke noget der stiger på passivsiden.\"", prompt:"Forklar, hvorfor påstanden er forkert, og hvad der reelt sker på begge sider af balancen.", checklist:["Genkender at et varesalg er en resultatpåvirkende postering, ikke en ombytning","Forklarer at tilgodehavendet (aktiv) stiger med salgsbeløbet","Forklarer at egenkapitalens resultat-del (passiv) stiger tilsvarende, så balancen fortsat stemmer"], questionVersion:1 },
      { id:"u34a-a7", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:3, tags:["moms","beregning"], scenario:"En virksomhed køber varer for 100 kr. + 25 % købsmoms (25 kr.) og betaler kontant.", prompt:"Hvor meget krediteres kassebeholdningen med i alt?", options:["100 kr.","25 kr.","125 kr.","75 kr."], correct:2, explanation:"Varelager debiteres 100, købsmoms debiteres 25 — tilsammen betales 125 kr. kontant, så kassebeholdningen krediteres 125 kr.", questionVersion:1 },
      { id:"u34a-a8", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:2, tags:["moms","beregning"], scenario:"Virksomheden sælger varer for 400 kr. + 25 % salgsmoms og har i samme periode købt varer med 25 kr. i købsmoms.", prompt:"Hvor meget skal virksomheden afregne til Skat i moms?", options:["100 kr.","75 kr.","125 kr.","25 kr."], correct:1, explanation:"Salgsmoms er 25 % af 400 = 100 kr. Momsafregning = salgsmoms − købsmoms = 100 − 25 = 75 kr.", questionVersion:1 },
      { id:"u34a-a9", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:2, tags:["afskrivning","beregning"], scenario:"Inventar er købt for 550.000 kr. med forventet scrapværdi 100.000 kr. om 5 år og afskrives lineært.", prompt:"Hvad er den årlige afskrivning?", options:["110.000 kr.","90.000 kr.","100.000 kr.","50.000 kr."], correct:1, explanation:"Lineær afskrivning = (550.000 − 100.000) / 5 = 90.000 kr. om året.", questionVersion:1 },
      { id:"u34a-a10", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"mc", difficulty:3, tags:["afskrivning","beregning"], scenario:"Samme inventar som ovenfor (årlig afskrivning 90.000 kr.) er nu afskrevet i 2 år.", prompt:"Hvad er den bogførte værdi efter år 2?", options:["550.000 kr.","460.000 kr.","370.000 kr.","280.000 kr."], correct:2, explanation:"Akkumulerede afskrivninger efter 2 år = 180.000 kr. Bogført værdi = 550.000 − 180.000 = 370.000 kr.", questionVersion:1 },
      { id:"u34a-a11", goalId:"uge34a-g2", weekId:"uge34a", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Bogføringssystemet (Uge 34, kap. 6)", type:"self", difficulty:4, tags:["afskrivning","modelvalg"], prompt:"Hvorfor bogføres afskrivninger på en separat \"akkumulerede afskrivninger\"-konto i stedet for at trække beløbet direkte fra aktivkontoen? Hvilken information ville gå tabt, hvis man gjorde det?", checklist:["Forklarer at aktivkontoen (anskaffelsesprisen) forbliver synlig og uændret", "Forklarer at den akkumulerede afskrivningskonto viser den samlede værdiforringelse til dato", "Konkluderer at man ellers ville miste overblikket over enten anskaffelsesprisen eller værdiforringelsen"], questionVersion:1 },
    ],
  },

  // ======================================================================
  // UGE 34b — Vurdering af årsrapporten
  // Source: vurdering-af-aarsrapporten.md (kap. 8 + 5.5.4)
  // ======================================================================
  uge34b: {
    basis: [
      { id:"u34b-b1", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:1, tags:["regnskabsklasser"], prompt:"Hvilken regnskabsklasse hører børsnoterede aktieselskaber som Matas til?", options:["Klasse A","Klasse B","Klasse C","Klasse D"], correct:3, explanation:"Klasse D dækker børsnoterede og statslige aktieselskaber.", questionVersion:1 },
      { id:"u34b-b2", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:1, tags:["regnskabsklasser"], prompt:"Hvad kendetegner klasse A-virksomheder?", options:["Store, børsnoterede selskaber","Virksomheder med personligt ansvar, fx enkeltmandsvirksomheder", "Kun statslige virksomheder","Mellemstore virksomheder"], correct:1, explanation:"Klasse A dækker virksomheder med personligt ansvar, som enkeltmandsvirksomheder og I/S.", questionVersion:1 },
      { id:"u34b-b3", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"tf", difficulty:1, tags:["regnskabsklasser"], prompt:"En virksomhed skal altid følge kravene for netop sin egen regnskabsklasse — hverken mere eller mindre.", correct:false, explanation:"Virksomheden skal minimum følge reglerne for sin egen og lavere klasser, men kan frivilligt vælge at følge en højere klasses (strengere) regler.", questionVersion:1 },
      { id:"u34b-b4", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:1, tags:["aarsrapport-indhold"], prompt:"Hvilken del af årsrapporten er kun lovpligtig for regnskabsklasse C og D?", options:["Ledelsesberetningen","Pengestrømsopgørelsen","Balancen","Resultatopgørelsen"], correct:1, explanation:"Pengestrømsopgørelsen er kun lovpligtig for regnskabsklasse C og D, ligesom revisionspåtegningen.", questionVersion:1 },
      { id:"u34b-b5", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["retvisende-billede"], prompt:"Hvad er det overordnede princip i årsregnskabsloven (ÅRL § 11, stk. 1)?", options:["Årsrapporten skal minimere skattebetalingen","Årsrapporten skal give et retvisende billede af virksomhedens aktiver, passiver, finansielle stilling og resultat","Årsrapporten skal kun vise positive resultater","Årsrapporten skal udelukkende følge internationale regler"], correct:1, explanation:"Det retvisende billede er ÅRL's grundlæggende krav og vejer tungest, hvis det kolliderer med lovens detailbestemmelser i et konkret tilfælde.", questionVersion:1 },
      { id:"u34b-b6", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"match", difficulty:2, tags:["retvisende-billede"], prompt:"Match den grundlæggende forudsætning (ÅRL §§ 11-14) med dens betydning.", terms:["Going concern","Periodisering","Kontinuitet","Bruttoværdi"], defs:["Regnskabet udarbejdes under forudsætning af, at virksomheden fortsætter","Indtægter/omkostninger hører til det år, de vedrører","Samme regnskabspraksis bruges år for år, så regnskaber kan sammenlignes","Hver post værdiansættes for sig og må ikke modregnes med andre"], explanation:"De fire forudsætninger sikrer hver især en del af, at regnskabet giver et pålideligt og sammenligneligt billede.", questionVersion:1 },
      { id:"u34b-b7", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:1, tags:["revision"], prompt:"Hvem rapporterer revisor direkte til, og hvorfor?", options:["Direktionen, fordi den driver virksomheden","Bestyrelsen, så direktionen ikke kan tilbageholde information","Aktionærerne direkte, uden om ledelsen","Erhvervsstyrelsen alene"], correct:1, explanation:"Revisor er ejernes og offentlighedens tillidsrepræsentant og skal være uafhængig — derfor rapporterer revisor til bestyrelsen, ikke direktionen.", questionVersion:1 },
      { id:"u34b-b8", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"tf", difficulty:1, tags:["revision"], prompt:"De fleste revisionspåtegninger indeholder forbehold.", correct:false, explanation:"De fleste revisionspåtegninger er uden forbehold (\"blank påtegning\") — forhold der opstår under revisionen bringes typisk i orden inden regnskabsaflæggelsen.", questionVersion:1 },
      { id:"u34b-b9", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["pengestroem"], prompt:"Hvilken rækkefølge følger pengestrømsopgørelsens tre dele?", options:["Finansiering → investering → drift","Drift → investering → finansiering","Investering → drift → finansiering","Der er ingen fast rækkefølge"], correct:1, explanation:"Pengestrømsopgørelsen opdeles i denne rækkefølge: drift, investering, finansiering.", questionVersion:1 },
      { id:"u34b-b10", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["pengestroem"], prompt:"Hvorfor lægges afskrivninger til resultat af primær drift i pengestrømsopgørelsens driftsdel?", options:["Fordi afskrivninger er en fejl i regnskabet","Fordi afskrivninger ikke er en kontant udgift — betalingen skete allerede ved anskaffelsen","Fordi afskrivninger altid er negative","Fordi det kræves af Skat"], correct:1, explanation:"Afskrivninger er en regnskabsmæssig omkostning, men ingen kontant betaling sker i perioden — pengene blev brugt, da aktivet blev anskaffet.", questionVersion:1 },
      { id:"u34b-b11", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:1, tags:["corporate-governance"], prompt:"Hvad betyder \"comply-or-explain\" i Nasdaq Copenhagens anbefalinger til god selskabsledelse?", options:["Virksomheden skal altid følge alle anbefalinger", "Virksomheden skal enten følge anbefalingerne eller forklare, hvorfor den ikke gør", "Anbefalingerne er et lovkrav uden undtagelser", "Kun klasse D-virksomheder må afvige"], correct:1, explanation:"Princippet er, at virksomhederne enten følger anbefalingerne eller forklarer, hvorfor de ikke gør det — det er (endnu) ikke et lovkrav.", questionVersion:1 },
      { id:"u34b-b12", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:1, tags:["indsendelse"], prompt:"Hvor længe har en klasse B- eller C-virksomhed efter regnskabsårets afslutning til at indsende årsrapporten til Erhvervsstyrelsen?", options:["3 måneder","4 måneder","6 måneder","12 måneder"], correct:2, explanation:"Klasse B og C skal indsende senest 6 måneder efter regnskabsårets afslutning — klasse D har kun 4 måneder.", questionVersion:1 },
      { id:"u34b-b13", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"tf", difficulty:2, tags:["revisionspligt"], prompt:"En klasse B-virksomhed er altid fritaget for revisionspligt, uanset omsætning og balance.", correct:false, explanation:"Fritagelse kræver, at virksomheden i to på hinanden følgende år ikke overskrider grænserne for balancesum, omsætning og ansatte — og risikobranche-virksomheder over en vis omsætning er altid revisionspligtige.", questionVersion:1 },
      { id:"u34b-b14", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["csr-esg"], prompt:"Hvilke virksomheder skal ifølge kap. 8.6 supplere ledelsesberetningen med en CSR-/ESG-redegørelse?", options:["Alle klasse A-virksomheder","Kun børsnoterede banker","Store virksomheder i klasse C og alle i klasse D","Ingen — det er altid frivilligt"], correct:2, explanation:"Store virksomheder i klasse C og alle i klasse D skal supplere med en CSR-/ESG-redegørelse om bl.a. miljø-, sociale og personaleforhold.", questionVersion:1 },
      { id:"u34b-b15", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["revision"], prompt:"Hvornår tager revisor typisk forbehold i revisionspåtegningen?", options:["Når virksomheden har haft et underskud", "Når regnskabet ikke opfylder kravet om et retvisende billede, eller er behæftet med fejl/mangler", "Når virksomheden skifter revisor", "Når årsrapporten aflægges i en fremmed valuta"], correct:1, explanation:"Revisor tager forbehold bl.a. hvis regnskabet ikke giver et retvisende billede, er behæftet med fejl/mangler, eller hvis going concern-forudsætningen er tvivlsom.", questionVersion:1 },
      { id:"u34b-b16", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"tf", difficulty:1, tags:["aarsrapport-indhold"], prompt:"Årsrapporten kan opgøres i en anden valuta end DKK, hvis en væsentlig del af køb/salg sker i den valuta.", correct:true, explanation:"Fx opgør Vestas i EUR og Maersk i USD, fordi en væsentlig del af deres køb/salg sker i disse valutaer.", questionVersion:1 },
      { id:"u34b-b17", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["lovgrundlag"], prompt:"Hvilke tre love/regelsæt danner det lovmæssige udgangspunkt for årsregnskabet?", options:["Kun årsregnskabsloven","Bogføringsloven, bogføringsbekendtgørelsen og årsregnskabsloven","Kun skattelovgivningen","EU's taksonomiforordning alene"], correct:1, explanation:"Bogføringsloven, bogføringsbekendtgørelsen og årsregnskabsloven (ÅRL) er det lovmæssige udgangspunkt; FSR uddyber med regnskabsvejledninger.", questionVersion:1 },
    ],
    anvendelse: [
      { id:"u34b-a1", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"self", difficulty:3, tags:["case","pengestroem"], prompt:"Forklar med egne ord, hvorfor en virksomhed kan gå konkurs, selvom resultatopgørelsen viser overskud.", checklist:["Forklarer at overskud er et regnskabsmæssigt begreb (indtægter minus omkostninger), ikke kontanter i kassen","Nævner et konkret eksempel, fx sene betalinger fra kunder eller for meget kapital bundet i varelager","Kobler det til, at det netop er det, pengestrømsopgørelsen viser, som resultatopgørelsen ikke gør"], questionVersion:1 },
      { id:"u34b-a2", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:3, tags:["pengestroem","beregning"], scenario:"En virksomheds pengestrømsopgørelse viser: resultat af primær drift 125, + afskrivninger 45, ændring i varelagre −40 (lageret er vokset), ændring i debitorer +30 (debitorerne er faldet), ændring i leverandørgæld +20, ændring i anden kort gæld −15.", prompt:"Hvad bliver pengestrømmen fra primær drift?", options:["125","170","165","210"], correct:2, explanation:"125 + 45 − 40 + 30 + 20 − 15 = 165.", questionVersion:1 },
      { id:"u34b-a3", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:3, tags:["pengestroem","beregning"], scenario:"Pengestrøm fra primær drift er 165. Renteomkostninger er −12 og betalt selskabsskat er −20.", prompt:"Hvad bliver pengestrøm fra driftsaktivitet?", options:["197","153","133","177"], correct:2, explanation:"165 − 12 − 20 = 133.", questionVersion:1 },
      { id:"u34b-a4", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"tf", difficulty:2, tags:["revision","fejlslutning"], scenario:"En revisor opdager under revisionen mindre uklarheder, som bliver rettet, inden årsrapporten offentliggøres.", prompt:"Denne virksomhed vil derfor med stor sandsynlighed ende med en revisionspåtegning uden forbehold.", correct:true, explanation:"De fleste forhold, revisor finder undervejs, bringes i orden inden regnskabsaflæggelsen — derfor er en blank påtegning (uden forbehold) det almindelige udfald.", questionVersion:1 },
      { id:"u34b-a5", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"self", difficulty:4, tags:["case","modelvalg"], scenario:"Et selskab i klasse C overvejer at afvige fra ÅRL's detailbestemmelser om en bestemt post, fordi ledelsen mener, at den lovbestemte metode giver et misvisende billede af virksomhedens reelle økonomiske stilling.", prompt:"Er det tilladt, og hvad kræver ÅRL i så fald af virksomheden?", checklist:["Genkender at det retvisende billede vejer tungest, hvis det kolliderer med lovens detailbestemmelser","Konkluderer at afvigelsen derfor kan være tilladt","Nævner kravet om, at forholdet skal forklares i en note"], questionVersion:1 },
      { id:"u34b-a6", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["ledelsesberetning"], scenario:"Et stort selskab i klasse C skal udarbejde sin ledelsesberetning for året.", prompt:"Hvilket krav gælder for klasse C (og D), som IKKE gælder for klasse B?", options:["Ingen ledelsesberetning kræves overhovedet","Kun en kort beskrivelse af aktiviteter kræves","En uddybende beskrivelse efter ÅRL § 99, bl.a. af udvikling, forventninger og videnressourcer","Ledelsesberetningen skal altid revideres fuldt ud som balancen"], correct:2, explanation:"Klasse B har kun begrænsede krav (kort beskrivelse). Klasse C og D skal give en langt mere uddybende forståelse af virksomheden efter ÅRL § 99.", questionVersion:1 },
      { id:"u34b-a7", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"self", difficulty:3, tags:["case","interessenter"], scenario:"Årsregnskabsloven har til hensigt at tage hensyn til en bred kreds af regnskabsbrugere.", prompt:"Nævn mindst fire forskellige typer regnskabsbrugere, og forklar kort, hvorfor deres informationsbehov kan være forskelligt.", checklist:["Nævner mindst fire brugertyper (fx ejere, kreditorer, medarbejdere, kunder, myndigheder)","Forklarer at deres informationsbehov er forskelligt (fx kreditor vil vide om tilbagebetalingsevne, medarbejder om jobsikkerhed)","Kobler det til interessentmodellen"], questionVersion:1 },
      { id:"u34b-a8", goalId:"uge34b-g1", weekId:"uge34b", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Vurdering af årsrapporten (Uge 34.2)", type:"mc", difficulty:2, tags:["fejlslutning"], scenario:"En medstuderende siger: \"Ledelsesberetningen bliver revideret på nøjagtig samme måde som resultatopgørelsen og balancen.\"", prompt:"Hvad er fejlen i denne påstand?", options:["Der er ingen fejl", "Ledelsesberetningen revideres IKKE — revisor gennemlæser den kun og kontrollerer, at den stemmer overens med regnskabet", "Ledelsesberetningen findes ikke i årsrapporten", "Kun klasse A-virksomheder har en ledelsesberetning"], correct:1, explanation:"Ledelsesberetningen revideres ikke; revisor skal blot gennemlæse den og kontrollere overensstemmelse med regnskabet — det er en anden kontrol end selve revisionen af tallene.", questionVersion:1 },
    ],
  },

  // ======================================================================
  // UGE 35 — Rentabilitetsanalyse (Du-Pont-modellen)
  // Source: rentabilitetsanalyse.md
  // ======================================================================
  uge35: {
    basis: [
      { id:"u35-b1", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"flash", difficulty:1, tags:["dupont","formel"], prompt:"Du-Pont-identiteten: Hvordan beregnes afkastningsgraden?", back:"AG = OG × AOH.", questionVersion:1 },
      { id:"u35-b2", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:1, tags:["dupont"], prompt:"Hvad viser overskudsgraden?", options:["Hvor mange gange aktiverne omsættes","Hvor stor en del af omsætningen der bliver til resultat af primær drift","Hvor meget gæld virksomheden har","Hvor stor en del af aktiverne der er anlægsaktiver"], correct:1, explanation:"OG = resultat af primær drift / nettoomsætning og viser indtjeningen pr. omsætningskrone.", questionVersion:1 },
      { id:"u35-b3", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"flash", difficulty:1, tags:["dupont","formel"], prompt:"Formel: Aktivernes omsætningshastighed?", back:"AOH = Nettoomsætning / Gennemsnitlige aktiver.", questionVersion:1 },
      { id:"u35-b4", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:1, tags:["gearing"], prompt:"Hvad kaldes forskellen AG − FKF?", options:["Bruttomarginen","Rentemarginalen","Sikkerhedsmarginen","Kapacitetsgraden"], correct:1, explanation:"Rentemarginalen viser forskellen mellem afkastet på kapitalen og prisen på fremmedkapitalen.", questionVersion:1 },
      { id:"u35-b5", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"tf", difficulty:2, tags:["gearing"], prompt:"En positiv rentemarginal betyder, at fremmedkapitalen kan løfte egenkapitalens forrentning.", correct:true, explanation:"Når AG er højere end FKF, bidrager gældsfinansieringen positivt til EKF via den finansielle løftestang.", questionVersion:1 },
      { id:"u35-b6", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"match", difficulty:2, tags:["dupont","formel"], prompt:"Match nøgletal og formel.", terms:["OG","AOH","EKF","FKF"], defs:["Resultat af primær drift / Nettoomsætning","Nettoomsætning / Gennemsnitlige aktiver","Årets resultat / Gennemsnitlig egenkapital","Renteomkostninger / Gennemsnitlig fremmedkapital"], explanation:"De fire nøgletal forbinder drift, kapitaludnyttelse, ejernes afkast og låneomkostningen.", questionVersion:1 },
      { id:"u35-b7", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:1, tags:["gearing","formel"], prompt:"Hvad kaldes forholdet gennemsnitlig fremmedkapital / gennemsnitlig egenkapital?", options:["Rentemarginal","Finansiel gearing","Overskudsgrad","Soliditetsgrad"], correct:1, explanation:"Finansiel gearing er forholdet mellem fremmedkapital og egenkapital — den forstærker løftestangseffekten i begge retninger.", questionVersion:1 },
      { id:"u35-b8", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"tf", difficulty:2, tags:["gearing"], prompt:"Høj finansiel gearing forstærker kun løftestangseffekten, når den er positiv — ikke når den er negativ.", correct:false, explanation:"Høj gearing forstærker løftestangen i BÅDE positiv og negativ retning, alt efter om rentemarginalen er positiv eller negativ.", questionVersion:1 },
      { id:"u35-b9", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Egenkapitalens forrentning (EKF)?", back:"EKF = Årets resultat / Gennemsnitlig egenkapital.", questionVersion:1 },
      { id:"u35-b10", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Fremmedkapitalens forrentning (FKF)?", back:"FKF = Renteomkostninger / Gennemsnitlig fremmedkapital.", questionVersion:1 },
      { id:"u35-b11", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35 + begrebs- og formelsamling", type:"mc", difficulty:1, tags:["synonym"], prompt:"Hvad er den engelske forkortelse/synonym for egenkapitalens forrentning?", options:["ROA","ROE","ROI","ROIC"], correct:1, explanation:"Egenkapitalens forrentning svarer til ROE (Return on Equity).", questionVersion:1 },
      { id:"u35-b12", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:2, tags:["formel"], prompt:"Hvilken formel udtrykker den finansielle løftestang?", options:["EKF før skat = AG − FKF","EKF før skat = AG + (AG − FKF) × (Gennemsnitlig fremmedkapital / Gennemsnitlig egenkapital)","EKF før skat = OG × AOH","EKF før skat = FKF × gearing"], correct:1, explanation:"Løftestangsformlen lægger rentemarginalen (AG − FKF) ganget med gearingen oveni afkastningsgraden.", questionVersion:1 },
    ],
    anvendelse: [
      { id:"u35-a1", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:2, tags:["dupont","beregning"], scenario:"En virksomhed har OG på 9,4 % og AOH på 0,73.", prompt:"Hvad er afkastningsgraden omtrent?", options:["6,9 %","9,4 %","12,9 %","0,69 %"], correct:0, explanation:"AG = 9,4 % × 0,73 ≈ 6,9 %.", questionVersion:1 },
      { id:"u35-a2", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:3, tags:["dupont","modelvalg"], prompt:"Hvordan kan to virksomheder få samme AG med meget forskellige forretningsmodeller?", options:["AG afhænger ikke af driften","En høj OG kan opveje en lav AOH og omvendt","De skal have samme omsætning","De skal have samme gæld"], correct:1, explanation:"Du-Pont-identiteten gør det muligt at nå samme AG via forskellige kombinationer af margin og kapitaludnyttelse.", questionVersion:1 },
      { id:"u35-a3", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"tf", difficulty:3, tags:["gearing"], scenario:"AG falder under FKF, mens den finansielle gearing er høj.", prompt:"Den finansielle løftestang vil i denne situation typisk trække EKF ned.", correct:true, explanation:"Når rentemarginalen er negativ, forstærker høj gearing den negative virkning på ejernes afkast.", questionVersion:1 },
      { id:"u35-a4", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"self", difficulty:4, tags:["case","dupont","gearing"], scenario:"Du får OG, AOH, FKF og finansiel gearing for en virksomhed over tre år.", prompt:"Lav en kort eksamenskommentar til udviklingen i AG og EKF.", checklist:["Beregner eller forbinder AG med OG × AOH","Vurderer rentemarginalens fortegn","Forklarer gearingens virkning og konkluderer på udviklingen"], questionVersion:1 },
      { id:"u35-a5", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:3, tags:["gearing","beregning"], scenario:"En virksomhed har AG = 10 % og en gennemsnitlig gældsrente på 5 %.", prompt:"Hvad betyder det for ejernes afkast, at virksomheden bruger fremmedkapital i finansieringen?", options:["Gælden er ligegyldig for ejernes afkast","Positiv gearing — virksomheden tjener mere på kapitalen (10 %) end den betaler for lånet (5 %)","Negativ gearing, fordi al gæld er risikabel","Det kan ikke afgøres uden egenkapitalens størrelse"], correct:1, explanation:"AG (10 %) er højere end gældsrenten (5 %), så virksomheden har positiv gearing: lånefinansieringen trækker EKF op.", questionVersion:1 },
      { id:"u35-a6", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:3, tags:["dupont","case"], scenario:"Matas-eksemplet: bruttoresultat 2.014, kapacitetsomkostninger 1.591.", prompt:"Hvad er resultat af primær drift?", options:["3.605","1.591","423","2.014"], correct:2, explanation:"Resultat af primær drift = bruttoresultat − kapacitetsomkostninger = 2.014 − 1.591 = 423.", questionVersion:1 },
      { id:"u35-a7", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"self", difficulty:4, tags:["modelvalg","fejlslutning"], prompt:"En medstuderende konkluderer: \"Virksomhed A har højere overskudsgrad end virksomhed B, så A er den bedre forretning.\" Forklar hvorfor denne konklusion er for forhastet ud fra Du-Pont-modellen.", checklist:["Genkender at OG kun er den ene halvdel af AG = OG × AOH","Forklarer at B kan have en højere AOH, som opvejer den lavere OG","Konkluderer at man ikke kan vurdere \"bedre forretning\" på OG alene — AG (eller EKF) er det mere retvisende samlede mål"], questionVersion:1 },
      { id:"u35-a8", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35 (Matas-eksempel) — se QUIZ-ARCHITECTURE.md §6.3 for en note om ±1 afrunding", type:"mc", difficulty:2, tags:["beregning"], scenario:"Matas' gennemsnitlige varebeholdninger er 901, tilgodehavender 121 og likvide beholdninger 33 (mio. kr., alle omsætningsaktiver).", prompt:"Hvad er de gennemsnitlige omsætningsaktiver i alt?", options:["901","1.022","1.055","155"], correct:2, explanation:"901 + 121 + 33 = 1.055 mio. kr. Kildenoten selv angiver 1.054 — en ét-tals afrundingsforskel, fordi hvert af de tre delbeløb er selvstændigt afrundede tal. Regner du selv de tre tal sammen, er 1.055 det matematisk korrekte svar.", questionVersion:2 },
      { id:"u35-a9", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35 (Matas-eksempel)", type:"mc", difficulty:3, tags:["beregning"], scenario:"Matas: AG = 6,9 %, FKF = 1,7 %, finansiel gearing ≈ 0,89.", prompt:"Hvad er EKF før skat omtrent, ifølge løftestangsformlen?", options:["6,9 %","8,6 %","11,5 %","1,7 %"], correct:2, explanation:"EKF før skat = 6,9 % + (6,9 % − 1,7 %) × 0,89 = 6,9 % + 5,2 procentpoint × 0,89 ≈ 11,5 %.", questionVersion:1 },
      { id:"u35-a10", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35 (Matas-eksempel)", type:"tf", difficulty:2, tags:["fejlslutning"], prompt:"EKF efter skat er altid højere end EKF før skat.", correct:false, explanation:"Tværtimod: Matas' EKF før skat er 11,4-11,5 %, mens EKF efter skat er 8,6 % — skatten reducerer altid egenkapitalens forrentning efter skat.", questionVersion:1 },
      { id:"u35-a11", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"self", difficulty:3, tags:["case"], scenario:"En bank overvejer at yde et selskab et lån til en rente på 7 %, mens selskabets afkastningsgrad er 5 %.", prompt:"Er det en god idé for selskabets ejere at optage lånet ud fra rentemarginal-logikken? Begrund.", checklist:["Beregner eller vurderer rentemarginalen (AG − rente = 5 % − 7 % = −2 procentpoint)","Konkluderer at rentemarginalen er negativ", "Forklarer at negativ gearing trækker EKF ned — jo mere selskabet låner til denne rente, jo værre bliver det for ejernes afkast"], questionVersion:1 },
      { id:"u35-a12", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"mc", difficulty:2, tags:["formel"], prompt:"Hvad viser fremmedkapitalens forrentning (FKF) i praksis?", options:["Hvor meget virksomheden tjener på egenkapitalen","Hvad virksomheden i gennemsnit betaler i rente af sin gæld","Hvor stor omsætningen er","Hvor mange gange aktiverne omsættes"], correct:1, explanation:"FKF = renteomkostninger / gennemsnitlig fremmedkapital og viser den gennemsnitlige pris, virksomheden betaler for sin lånte kapital.", questionVersion:1 },
      { id:"u35-a13", goalId:"uge35-g1", weekId:"uge35", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 35", type:"tf", difficulty:2, tags:["fejlslutning"], prompt:"Rentemarginalen (AG − FKF) kan aldrig blive negativ i praksis.", correct:false, explanation:"Rentemarginalen kan sagtens blive negativ, hvis afkastningsgraden falder under fremmedkapitalens forrentning — det er netop dét, der udløser negativ gearing.", questionVersion:1 },
    ],
  },

  // ======================================================================
  // UGE 36 — Indtjeningsanalyse
  // Source: indtjeningsanalyse.md
  // ======================================================================
  uge36: {
    basis: [
      { id:"u36-b1", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Bruttoavanceprocent/bruttomargin?", back:"Bruttofortjeneste / Omsætning × 100.", questionVersion:1 },
      { id:"u36-b2", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:1, tags:["ebitda"], prompt:"Hvorfor er EBITDA interessant i en indtjeningsanalyse?", options:["Det inkluderer kun skat","Det viser resultat før af- og nedskrivninger, som ikke er kontante omkostninger","Det er det samme som omsætning","Det måler kun gælden"], correct:1, explanation:"EBITDA isolerer driften før af- og nedskrivninger og giver derfor et andet blik på indtjeningen og likviditetspåvirkningen.", questionVersion:1 },
      { id:"u36-b3", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"tf", difficulty:2, tags:["indekstal","fejlslutning"], prompt:"Et stort procentvist indeksspring på et lille beløb kan uden videre vægte mere end en mindre ændring på et stort beløb.", correct:false, explanation:"Indekstal skal altid vurderes sammen med de absolutte kronebeløb.", questionVersion:1 },
      { id:"u36-b4", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Driftsmæssig gearing?", back:"Kapacitetsomkostninger / Samlede driftsomkostninger × 100.", questionVersion:1 },
      { id:"u36-b5", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:1, tags:["kapacitetsgrad"], prompt:"Hvordan angives kapacitetsgraden?", options:["Som antal gange","Altid i procent","I kroner pr. medarbejder","Som en indeksværdi med basis 100"], correct:0, explanation:"KG = bruttoresultat / kapacitetsomkostninger og angives som antal gange.", questionVersion:1 },
      { id:"u36-b6", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"match", difficulty:2, tags:["formel"], prompt:"Match nøgletal og det, det beskriver.", terms:["Bruttomargin","Driftsmæssig gearing","Nulpunktsomsætning","Sikkerhedsmargin"], defs:["Indtjening efter vareforbrug pr. omsætningskrone","Andelen af faste kapacitetsomkostninger i de samlede driftsomkostninger","Omsætningen hvor driftsresultatet netop er nul","Hvor meget omsætningen kan falde relativt, før nulpunktet nås"], explanation:"Nøgletallene går fra indtjeningens sammensætning til virksomhedens følsomhed over for omsætningsfald.", questionVersion:1 },
      { id:"u36-b7", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"tf", difficulty:2, tags:["fejlslutning"], prompt:"Finansielle omkostninger og skat indgår i de samlede driftsomkostninger, når driftsmæssig gearing beregnes.", correct:false, explanation:"Kilden afgrænser samlede driftsomkostninger til kapacitetsomkostninger plus vareforbrug; finansielle omkostninger og skat indgår ikke.", questionVersion:1 },
      { id:"u36-b8", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:1, tags:["kapacitetsomkostninger"], prompt:"Hvad indgår i kapacitetsomkostninger i en artsopdelt resultatopgørelse?", options:["Kun vareforbrug","Andre eksterne omkostninger, personaleomkostninger samt af- og nedskrivninger","Kun finansielle omkostninger","Kun skat"], correct:1, explanation:"I en artsopdelt resultatopgørelse består kapacitetsomkostninger af andre eksterne omkostninger, personaleomkostninger samt af- og nedskrivninger.", questionVersion:1 },
      { id:"u36-b9", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:1, tags:["indekstal","formel"], prompt:"Hvordan beregnes et indekstal?", options:["Beløb i år n minus beløb i år 1","Beløb i år n / Beløb i år 1 × 100","Beløb i år 1 / Beløb i år n × 100","Gennemsnittet af alle års beløb"], correct:1, explanation:"Indekstal = Beløb i år n / Beløb i år 1 × 100 — gør udviklingen sammenlignelig uafhængigt af kronestørrelse.", questionVersion:1 },
      { id:"u36-b10", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Nulpunktsomsætning?", back:"Kapacitetsomkostninger / Bruttomargin × 100.", questionVersion:1 },
      { id:"u36-b11", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Sikkerhedsmargin?", back:"(Faktisk omsætning − Nulpunktsomsætning) / Faktisk omsætning × 100.", questionVersion:1 },
      { id:"u36-b12", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:1, tags:["produktivitet"], prompt:"Hvilket nøgletal bruges som produktivitetsmål i indtjeningsanalysen?", options:["Soliditetsgrad","Omsætning eller driftsresultat pr. medarbejder","Likviditetsgrad II","Anlægsgrad"], correct:1, explanation:"Omsætning eller driftsresultat pr. medarbejder bruges som produktivitetsmål — Matas havde fx 2,07 mio. kr. i omsætning pr. medarbejder.", questionVersion:1 },
      { id:"u36-b13", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:2, tags:["kapacitetsomkostninger"], prompt:"Hvad indgår i kapacitetsomkostninger i en funktionsopdelt resultatopgørelse?", options:["Kun vareforbrug og finansielle omkostninger","Salgs- og distributionsomkostninger, administrationsomkostninger og evt. F&U-omkostninger","Kun personaleomkostninger","Skat og udbytte"], correct:1, explanation:"I en funktionsopdelt resultatopgørelse består kapacitetsomkostninger af salgs- og distributionsomkostninger, administrationsomkostninger og eventuelt forsknings- og udviklingsomkostninger — modsat den artsopdelte opstilling.", questionVersion:1 },
      { id:"u36-b14", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:1, tags:["samlede-driftsomkostninger"], prompt:"Hvad udgør de \"samlede driftsomkostninger\", som driftsmæssig gearing beregnes ud fra?", options:["Kapacitetsomkostninger plus vareforbrug","Kun finansielle omkostninger","Kapacitetsomkostninger plus skat","Vareforbrug plus skat"], correct:0, explanation:"Samlede driftsomkostninger er kapacitetsomkostninger plus vareforbrug — finansielle omkostninger og skat holdes udenfor.", questionVersion:1 },
    ],
    anvendelse: [
      { id:"u36-a1", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:3, tags:["gearing"], scenario:"To virksomheder mister 10 % af omsætningen. Virksomhed A har langt højere driftsmæssig gearing end B.", prompt:"Hvilken virksomhed får normalt det største relative fald i driftsresultatet?", options:["A, fordi flere omkostninger er faste","B, fordi flere omkostninger er faste","De rammes altid ens","Det kan kun afhænge af skatten"], correct:0, explanation:"Når en større del af omkostningerne er faste, forsvinder færre omkostninger sammen med salget, og driftsresultatet rammes hårdere.", questionVersion:1 },
      { id:"u36-a2", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:2, tags:["bruttomargin"], prompt:"Hvilken ændring kan forklare en lavere bruttomargin?", options:["Lavere indkøbspriser alt andet lige","Højere salgspriser alt andet lige","Forskydning mod produktgrupper med lavere margin","Lavere kapacitetsomkostninger"], correct:2, explanation:"Produktsammensætningen kan ændre den samlede bruttomargin, når produktgrupper har forskellige marginer.", questionVersion:1 },
      { id:"u36-a3", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:3, tags:["beregning"], scenario:"Faktisk omsætning er 4.490 mio. kr., og nulpunktsomsætningen er 3.547 mio. kr.", prompt:"Hvad er sikkerhedsmarginen omtrent?", options:["9,4 %","17,9 %","21,0 %","39,1 %"], correct:2, explanation:"(4.490 − 3.547) / 4.490 × 100 ≈ 21,0 %.", questionVersion:1 },
      { id:"u36-a4", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"self", difficulty:4, tags:["case"], scenario:"Du sammenligner en servicevirksomhed, en handelsvirksomhed og en produktionsvirksomhed.", prompt:"Hvordan kommenterer du forskelle i indtjeningsevne uden at overfortolke nøgletallene?", checklist:["Forklarer forskelle i omkostningsstruktur","Bruger både procenttal og absolutte beløb","Nævner at branche og virksomhedstype begrænser direkte sammenligning"], questionVersion:1 },
      { id:"u36-a5", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:2, tags:["beregning"], scenario:"Matas: bruttoresultat 2.014 mio. kr., omsætning 4.490 mio. kr.", prompt:"Hvad er bruttomarginen omtrent?", options:["25,7 %","44,9 %","55,1 %","223 %"], correct:1, explanation:"Bruttomargin = 2.014 / 4.490 × 100 ≈ 44,9 %.", questionVersion:1 },
      { id:"u36-a6", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"self", difficulty:4, tags:["fejlslutning","modelvalg"], scenario:"En medstuderende siger: \"EBITDA-marginen er højere end overskudsgraden, så virksomheden har åbenbart et problem med sine af- og nedskrivninger.\"", prompt:"Vurdér påstanden: er det nødvendigvis et problem, at EBITDA-marginen er højere end overskudsgraden?", checklist:["Forklarer at EBITDA-margin altid er ≥ overskudsgrad, fordi af- og nedskrivninger lægges til igen","Forklarer at det derfor er en matematisk regel, ikke automatisk et \"problem\"","Nævner at forskellens STØRRELSE (hvor kapitaltung virksomheden er) er det, der reelt skal vurderes"], questionVersion:1 },
      { id:"u36-a7", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36 (Matas-eksempel)", type:"mc", difficulty:3, tags:["beregning"], scenario:"Matas: resultat af primær drift 423 mio. kr., afskrivninger 381 mio. kr., omsætning 4.490 mio. kr.", prompt:"Hvad er EBITDA/omsætning (EBITDA-marginen) omtrent?", options:["9,4 %","17,9 %","8,5 %","44,9 %"], correct:1, explanation:"EBITDA = 423 + 381 = 804. EBITDA-margin = 804 / 4.490 × 100 ≈ 17,9 %.", questionVersion:1 },
      { id:"u36-a8", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36 (Matas-eksempel)", type:"mc", difficulty:2, tags:["beregning"], scenario:"Matas: bruttoresultat 2.014 mio. kr., kapacitetsomkostninger 1.591 mio. kr.", prompt:"Hvad er kapacitetsgraden (KG) omtrent?", options:["79,0 %","1,27 gange","2.014 gange","0,79 gange"], correct:1, explanation:"KG = bruttoresultat / kapacitetsomkostninger = 2.014 / 1.591 ≈ 1,27 — angivet som antal gange, ikke procent.", questionVersion:1 },
      { id:"u36-a9", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36 (Matas-eksempel)", type:"tf", difficulty:2, tags:["case"], scenario:"Matas' nulpunktsomsætning er 3.547 mio. kr., og den faktiske omsætning er 4.490 mio. kr.", prompt:"Matas kunne miste mere end 900 mio. kr. i omsætning, før driftsresultatet blev negativt.", correct:true, explanation:"4.490 − 3.547 = 943 mio. kr. — det er præcis det beløb, omsætningen kunne falde med, før nulpunktet nås.", questionVersion:1 },
      { id:"u36-a10", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"self", difficulty:3, tags:["case","modelvalg"], scenario:"To detailkæder har samme bruttomargin, men kæde A har en langt højere driftsmæssig gearing end kæde B.", prompt:"Hvilken kæde vil du forvente svinger mest i driftsresultatet ved omsætningsudsving, og hvorfor bør en investor kende forskellen, selv når bruttomarginen er ens?", checklist:["Forklarer at høj driftsmæssig gearing betyder en større andel faste kapacitetsomkostninger","Konkluderer at kæde A (høj gearing) svinger mest i driftsresultatet ved op- og nedgang i omsætning","Forklarer hvorfor bruttomargin alene ikke fanger denne følsomhedsforskel"], questionVersion:1 },
      { id:"u36-a11", goalId:"uge36-g1", weekId:"uge36", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note + officielt EØ-flowplan · Uge 36", type:"mc", difficulty:2, tags:["produktivitet"], scenario:"Matas: omsætning pr. medarbejder 2,07 mio. kr., driftsresultat pr. medarbejder 0,20 mio. kr.", prompt:"Hvad kan man bruge disse to tal til, hvis man sammenligner Matas med en anden detailkæde?", options:["Kun til at vurdere Matas' aktiekurs","Som et produktivitetsmål, der viser hvor meget omsætning/driftsresultat hver medarbejder genererer","Til at beregne soliditetsgraden","De er ikke sammenlignelige på tværs af virksomheder"], correct:1, explanation:"Omsætning/driftsresultat pr. medarbejder er et produktivitetsmål, der kan sammenlignes på tværs af virksomheder af forskellig størrelse.", questionVersion:1 },
    ],
  },

  // ======================================================================
  // UGE 37 — Kapitaltilpasning, Soliditet & Likviditet
  // Source: kapitaltilpasning-soliditet-likviditet.md (kap. 5.3 + 9.6.3-9.6.4)
  //
  // NOTE (documented correction): the note has since been extended to cover
  // kap. 5.3 (balancestruktur) in full — the app's earlier uge37-a4 open
  // reflection question, written when kap. 5.3 was still unread, is now
  // stale and has been replaced below with real, note-grounded questions
  // about the vertical/horizontal balance structure. See QUIZ-ARCHITECTURE.md.
  // ======================================================================
  uge37: {
    basis: [
      { id:"u37-b1", goalId:"uge37-g1", weekId:"uge37", subjectId:"eo", source:"note", type:"mc", difficulty:1, tags:["kapitaltilpasning"],
        prompt: "Hvad måler \"kapitaltilpasning\" bedst?",
        options: ["Hvor stort virksomhedens overskud er","Virksomhedens evne til at tilpasse sin aktivitet til den kapital, der er bundet","Hvor meget egenkapital virksomheden har","Virksomhedens samlede gæld"],
        correct: 1, explanation: "Kapitaltilpasning handler om, hvor godt aktiviteten (omsætningen) matcher den kapital, der er bundet — fx i anlægsaktiver og varelager — ikke størrelsen af overskud eller gæld i sig selv.", questionVersion:1 },
      { id:"u37-b2", goalId:"uge37-g1", weekId:"uge37", subjectId:"eo", source:"note", type:"tf", difficulty:2, tags:["kapitaltilpasning","fejlslutning"],
        prompt: "Jo flere gange en aktivpost \"omsættes\" pr. år, jo bedre er udnyttelsen — det gælder også for varekreditorer.",
        correct: false, explanation: "For varekreditorer (en gældspost) gælder det modsatte: en LAV omsætningshastighed er fordelagtig, fordi virksomheden så kan udskyde betalingen længere.", questionVersion:1 },
      { id:"u37-b3", goalId:"uge37-g1", weekId:"uge37", subjectId:"eo", source:"note", type:"flash", difficulty:1, tags:["formel"], prompt: "Formel: omsætningshastighed for anlægsaktiver?", back: "Omsætning / Samlede anlægsaktiver ultimo", questionVersion:1 },
      { id:"u37-b4", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", type:"flash", difficulty:1, tags:["formel","soliditet"], prompt: "Formel: Soliditetsgrad?", back: "(Egenkapital ultimo / Aktiver ultimo) × 100", questionVersion:1 },
      { id:"u37-b5", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", type:"flash", difficulty:1, tags:["formel"], prompt: "Formel: Anlægsgrad?", back: "(Anlægsaktiver ultimo / Balancesum ultimo) × 100", questionVersion:1 },
      { id:"u37-b6", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", type:"mc", difficulty:2, tags:["likviditet"],
        prompt: "Hvorfor er kravet til Likviditetsgrad II typisk højere end til Likviditetsgrad I?",
        options: ["Fordi Likviditetsgrad II ikke medregner kortfristet gæld","Fordi varebeholdninger — som kun tælles med i grad II — tager tid at omsætte til likvide midler","Fordi Likviditetsgrad I kun bruges af store virksomheder","Der er ingen reel forskel i praksis"],
        correct: 1, explanation: "Likviditetsgrad II tæller varebeholdninger med i tælleren. Da varebeholdninger tager tid at sælge og omsætte til kontanter, skal grad II være højere for reelt at dække den kortfristede gæld til tiden.", questionVersion:1 },
      { id:"u37-b7", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", type:"match", difficulty:2, tags:["formel"],
        prompt: "Match nøgletal til formel.",
        terms: ["Soliditetsgrad", "Anlægsgrad", "Likviditetsgrad I", "Likviditetsgrad II"],
        defs: ["(Egenkapital ultimo / Aktiver ultimo) × 100","(Anlægsaktiver ultimo / Balancesum ultimo) × 100","(Omsætningsaktiver ekskl. varebeholdninger ultimo / Kortfristede gældsforpligtelser ultimo) × 100","(Omsætningsaktiver ultimo / Kortfristede gældsforpligtelser ultimo) × 100"],
        explanation: "Alle fire bruger balancens \"ultimo\"-tal, men ser på forskellige ting: soliditet på hele kapitalstrukturen, anlægsgrad på bindingen i anlægsaktiver, og de to likviditetsgrader på kort sigt — med og uden varebeholdninger.", questionVersion:1 },
      { id:"u37-b8", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3)", type:"mc", difficulty:1, tags:["balancestruktur"], prompt:"Hvad undersøger den vertikale balancestruktur?", options:["Forholdet mellem enkelte aktiv- og passivgrupper","Forholdet mellem passivernes hovedgrupper (egenkapital vs. fremmedkapital)","Kun likviditeten","Kun anlægsaktivernes alder"], correct:1, explanation:"Den vertikale balancestruktur analyserer forholdet mellem passivernes hovedgrupper — egenkapital vs. fremmedkapital.", questionVersion:1 },
      { id:"u37-b9", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3)", type:"flash", difficulty:1, tags:["formel","balancestruktur"], prompt:"Formel: Kapitalbindingsgrad?", back:"(Anlægsaktiver ultimo × 100) / (Egenkapital ultimo + langfristet gæld ultimo) — bør være under 100.", questionVersion:1 },
      { id:"u37-b10", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3)", type:"tf", difficulty:2, tags:["balancestruktur"], prompt:"Soliditetsgrad plus gældsætningsgrad giver altid 100 %.", correct:true, explanation:"Gældsætningsgrad = 100 − soliditetsgrad, fordi aktiverne enten er finansieret af egenkapital eller fremmedkapital.", questionVersion:1 },
      { id:"u37-b11", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3)", type:"mc", difficulty:1, tags:["balancestruktur"], prompt:"Hvad undersøger den horisontale balancestruktur?", options:["Kun soliditeten","Forholdet mellem enkelte aktiv- og passivgrupper, fx om kortfristede aktiver dækker kortfristet gæld","Kun virksomhedens omsætning","Forholdet mellem egenkapital og fremmedkapital alene"], correct:1, explanation:"Den horisontale balancestruktur ser på forholdet mellem de enkelte aktiv- og passivgrupper, herunder kapitalbinding og likviditet.", questionVersion:1 },
      { id:"u37-b12", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3)", type:"flash", difficulty:1, tags:["formel"], prompt:"Formel: Gældsætningsgrad?", back:"(Fremmedkapital ultimo / Aktiver ultimo) × 100.", questionVersion:1 },
      { id:"u37-b13", goalId:"uge37-g1", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet", type:"mc", difficulty:1, tags:["kapitaltilpasning"], prompt:"Hvilke nøgletal måler kapitaltilpasningen ifølge kilden?", options:["Kun soliditetsgraden","Omsætningshastigheder for anlægsaktiver, varelager, varedebitorer og varekreditorer samt pengestrøm fra primær drift/omsætning","Kun likviditetsgraderne","Kun bruttoavanceprocenten"], correct:1, explanation:"Kapitaltilpasning måles ved omsætningshastigheder for de nævnte poster samt pengestrøm fra primær drift i forhold til omsætningen.", questionVersion:1 },
      { id:"u37-b14", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet", type:"mc", difficulty:1, tags:["soliditet"], prompt:"Hvorfor vurderer lån- og långivere en virksomheds soliditetsgrad?", options:["Fordi den viser dækningen for hele virksomhedens gæld","Fordi den viser virksomhedens omsætningsvækst","Fordi den erstatter behovet for et regnskab","Den bruges kun af aktionærer, aldrig af långivere"], correct:0, explanation:"Soliditetsgraden viser, hvor følsom virksomheden er over for tab, og dermed hvor godt egenkapitalen dækker den samlede gæld — centralt for långiveres risikovurdering.", questionVersion:1 },
    ],
    anvendelse: [
      { id:"u37-a1", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", type:"mc", difficulty:3, tags:["balancestruktur","case"],
        scenario: "Matas (2022/23): Soliditetsgrad = 53,5 %, Anlægsgrad = 82,8 %.",
        prompt: "Hvad fortæller forskellen mellem de to nøgletal (82,8 − 53,5 = 29,3 procentpoint) bedst?",
        options: ["At Matas har for høj gæld til at kunne overleve","At anlægsaktiverne ikke er fuldt dækket af egenkapitalen alene — resten er finansieret af langfristet fremmedkapital","At Matas' likviditet er i akut fare","At beregningen må være forkert, da tallene ikke bør afvige"],
        correct: 1, explanation: "Når anlægsgraden er højere end soliditetsgraden, er en del af anlægsaktiverne finansieret af andet end egenkapital — hos Matas af langfristet fremmedkapital. Det er ikke i sig selv et faresignal.", questionVersion:1 },
      { id:"u37-a2", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", type:"self", difficulty:4, tags:["case"],
        scenario: "Matas har relativt lave likviditetsgrader, men noten vurderer det ikke som et faresignal.",
        prompt: "Forklar med dine egne ord hvorfor — brug gerne konkrete detaljer fra casen.",
        checklist: ["Nævner at næsten hele varesalget hos Matas sker kontant","Forbinder det kontante salg til et løbende likviditetsflow, uafhængigt af lagerbindingen","Konkluderer at lave likviditetsgrader derfor ikke automatisk er farlige — det afhænger af forretningsmodellen"], questionVersion:1 },
      { id:"u37-a3", goalId:"uge37-g1", weekId:"uge37", subjectId:"eo", source:"note", type:"self", difficulty:3, tags:["fejlslutning"],
        scenario: "En virksomhed betaler sine leverandører meget hurtigt — dvs. har en høj omsætningshastighed for varekreditorer.",
        prompt: "Er det umiddelbart en fordel eller en ulempe for virksomhedens likviditet — og hvorfor?",
        checklist: ["Genkender at varekreditorer er en undtagelse fra hovedreglen om omsætningshastighed","Konkluderer at en HØJ omsætningshastighed her er en ulempe, fordi virksomheden betaler hurtigere end nødvendigt","Forbinder det til at en lavere omsætningshastighed normalt er likviditetsmæssigt bedre for virksomheden selv"], questionVersion:1 },
      { id:"u37-a4", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3, Matas-eksempel) — beregning korrigeret, se QUIZ-ARCHITECTURE.md §6.3", type:"mc", difficulty:3, tags:["beregning","balancestruktur"], scenario:"Matas' balance pr. 31.3.2023 (mio. kr.): anlægsaktiver 5.202, egenkapital 3.363, langfristet gæld 1.620.", prompt:"Hvad er kapitalbindingsgraden omtrent?", options:["82,8 %","100,7 %","104,4 %","53,6 %"], correct:2, explanation:"Kapitalbindingsgrad = 5.202 × 100 / (3.363 + 1.620) = 520.200 / 4.983 ≈ 104,4 %. Kildenoten selv angiver 100,7 % på dette ene sted, men det stemmer ikke med dens egne tal — 520.200 / 4.983 giver ca. 104,4 %, ikke 100,7 %. Dette spørgsmål bruger det korrekte, genberegnede tal.", questionVersion:2 },
      { id:"u37-a5", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3, Matas-eksempel) — beregning korrigeret, se QUIZ-ARCHITECTURE.md §6.3", type:"self", difficulty:4, tags:["case","modelvalg"], scenario:"Matas' kapitalbindingsgrad er ca. 104,4 % (5.202 × 100 / (3.363 + 1.620)) — altså over 100.", prompt:"Forklar konkret, hvad det betyder, og hvorfor det ikke nødvendigvis er alarmerende, når man ser det sammen med resten af balancestrukturanalysen.", checklist:["Forklarer at anlægsaktiverne er større end den langfristede kapital, der finansierer dem","Nævner at en del af anlægsaktiverne (ca. 4-5 procentpoint over 100) derfor reelt er finansieret med kortfristet gæld","Konkluderer at tallet bør ses sammen med andre kilder, fx pengestrømsopgørelsen og likviditetsudviklingen, frem for isoleret"], questionVersion:2 },
      { id:"u37-a6", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3, Matas-eksempel)", type:"mc", difficulty:3, tags:["beregning"], scenario:"Matas' balance: omsætningsaktiver 1.079 mio. kr. (heraf varebeholdninger 912), kortfristet gæld 1.297 mio. kr.", prompt:"Hvad er Likviditetsgrad I omtrent?", options:["83,2 %","12,9 %","46,4 %","100,7 %"], correct:1, explanation:"Likviditetsgrad I = (1.079 − 912) × 100 / 1.297 = 167 × 100 / 1.297 ≈ 12,9 %.", questionVersion:1 },
      { id:"u37-a7", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet", type:"self", difficulty:4, tags:["modelvalg","case"], scenario:"Matas' afkastningsgrad (6,9 %) ligger betydeligt over forrentningen af fremmedkapitalen (1,7 %). I 2023 opkøbte Matas det svenske skønhedsfirma Kicks, finansieret fuldt ud med gæld.", prompt:"Hvordan vil opkøbet alt andet lige påvirke soliditetsgraden i den kommende regnskabsperiode, og hvorfor giver den positive rentemarginal alligevel et argument for, at gearingen kan være fordelagtig?", checklist:["Konkluderer at soliditetsgraden vil falde, fordi passiverne vokser med mere fremmedkapital uden tilsvarende stigning i egenkapitalen","Forklarer at den positive rentemarginal (AG > FKF) betyder, at gearing løfter egenkapitalens forrentning","Balancerer begge pointer: lavere soliditet (højere risiko) mod en potentielt gunstig løftestangseffekt"], questionVersion:1 },
      { id:"u37-a8", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3, Matas-eksempel)", type:"mc", difficulty:2, tags:["beregning"], scenario:"Matas' balance: egenkapital 3.363, aktiver i alt 6.280 (mio. kr.).", prompt:"Hvad er soliditetsgraden omtrent?", options:["46,4 %","82,8 %","53,6 %","100,7 %"], correct:2, explanation:"Soliditetsgrad = 3.363 / 6.280 × 100 ≈ 53,6 %.", questionVersion:1 },
      { id:"u37-a9", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3, Matas-eksempel)", type:"mc", difficulty:2, tags:["beregning"], scenario:"Matas' soliditetsgrad er 53,6 %.", prompt:"Hvad er gældsætningsgraden?", options:["53,6 %","46,4 %","100 %","6,9 %"], correct:1, explanation:"Gældsætningsgrad = 100 − soliditetsgrad = 100 − 53,6 = 46,4 %.", questionVersion:1 },
      { id:"u37-a10", goalId:"uge37-g2", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet (kap. 5.3, Matas-eksempel)", type:"self", difficulty:3, tags:["case"], scenario:"Matas' pengestrøm fra driftsaktivitet var positiv med 8,5 mio. kr., og likviditeten steg fra 28,2 til 36,7 mio. kr. i årets løb.", prompt:"Hvorfor bør balancestrukturens nøgletal (fx likviditetsgraderne) altid krydstjekkes med pengestrømsopgørelsen, sådan som det gøres her for Matas?", checklist:["Forklarer at balancetal kun giver et øjebliksbillede (ultimo-tal)","Nævner at Matas' positive pengestrøm og stigende likviditet understøtter, at de lave likviditetsgrader ikke er alarmerende","Konkluderer generelt: et nøgletal isoleret set kan være misvisende uden et krydstjek mod andre kilder"], questionVersion:1 },
      { id:"u37-a11", goalId:"uge37-g1", weekId:"uge37", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Kapitaltilpasning, Soliditet & Likviditet", type:"mc", difficulty:3, tags:["fejlslutning"], scenario:"En analytiker konkluderer: \"Virksomhedens omsætningshastighed for varelageret er faldet, så det er udelukkende positivt, fordi virksomheden nu binder mindre kapital.\"", prompt:"Hvad er fejlen i denne konklusion?", options:["Der er ingen fejl — konklusionen er korrekt","En FALDENDE omsætningshastighed betyder normalt, at MERE kapital bindes i lageret i længere tid — det modsatte af, hvad analytikeren konkluderer","Omsætningshastighed har intet med lagerbinding at gøre","Omsætningshastighed kan aldrig falde"], correct:1, explanation:"En lav/faldende omsætningshastighed for et aktiv som varelager er normalt en ULEMPE — det betyder, at kapitalen bindes længere tid i lageret, ikke mindre.", questionVersion:1 },
    ],
  },

  // ======================================================================
  // UGE 39 — Budgettering
  // Source: budgettering.md (kap. 11+12)
  //
  // NOTE: the source note itself flags an unresolved numeric discrepancy in
  // its Nordlys A/S example (139.000 − 241.000 = −102.000, not the −170.750
  // the note's own text concludes). That specific figure is therefore NOT
  // used in any graded question below — see QUIZ-ARCHITECTURE.md.
  // ======================================================================
  uge39: {
    basis: [
      { id:"u39-b1", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:1, tags:["budget"], prompt:"Hvad er et budget, ifølge kilden?", options:["Et regnskab for sidste år","Et dokument med en økonomisk konsekvensbeskrivelse af den handlingsplan, virksomheden ønsker at iværksætte", "Kun en oversigt over medarbejdere","Et lovkrav for alle virksomheder"], correct:1, explanation:"Budget kaldes også \"fremtidens regnskab\" — en økonomisk konsekvensbeskrivelse af den planlagte handling.", questionVersion:1 },
      { id:"u39-b2", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:1, tags:["budgetmodel"], prompt:"Hvilke tre budgetter består den samlede budgetmodel af?", options:["Salgs-, indkøbs- og lønbudget","Resultat-, likviditets- og balancebudget","Kun resultatbudget og likviditetsbudget","Budget for hver afdeling"], correct:1, explanation:"Den samlede budgetmodel består af resultatbudget, likviditetsbudget og balancebudget, som hænger indbyrdes sammen.", questionVersion:1 },
      { id:"u39-b3", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:2, tags:["budgetmodel"], prompt:"Hvilket nøgletal er det centrale bindeled mellem resultatbudgettet og likviditetsbudgettet?", options:["Dækningsbidraget","Indtjeningsbidraget","Årets resultat","Bruttofortjenesten"], correct:1, explanation:"Indtjeningsbidraget går fra resultatbudgettet ind i likviditetsbudgettet som første post.", questionVersion:1 },
      { id:"u39-b4", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"match", difficulty:2, tags:["resultatbudget"], prompt:"Match posten i resultatbudgettet med, hvad den fører frem til.", terms:["Omsætning − variable omkostninger","Dækningsbidrag − kontante kapacitetsomkostninger","Indtjeningsbidrag − afskrivninger","Resultat før renter +/- nettorenter − skat"], defs:["Dækningsbidrag","Indtjeningsbidrag","Resultat før renter","Årets resultat"], explanation:"Opstillingen går fra omsætning gennem dækningsbidrag og indtjeningsbidrag til årets resultat.", questionVersion:1 },
      { id:"u39-b5", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:2, tags:["likviditetsbudget"], prompt:"Hvad kendetegner ind- og udbetalingsmodellen for likviditetsbudgettet, i modsætning til beholdningsforskydningsmodellen?", options:["Den bygger på resultatopgørelsens periodiserede poster", "Den opgør de faktiske ind- og udbetalinger direkte, periode for periode", "Den bruges kun til balancebudgettet", "Den kan ikke bruges til at vurdere likviditetsbehov"], correct:1, explanation:"Ind- og udbetalingsmodellen registrerer de faktiske betalingsstrømme direkte, uafhængigt af resultatopgørelsens periodisering.", questionVersion:1 },
      { id:"u39-b6", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"tf", difficulty:1, tags:["budgetkontrol"], prompt:"En budgetafvigelse beregnes som Budget minus Regnskab.", correct:false, explanation:"Afvigelsen beregnes som Regnskab − Budget.", questionVersion:1 },
      { id:"u39-b7", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:1, tags:["budgetteringsforloeb"], prompt:"Hvad sker der i trin 1 af budgetteringsforløbets 8 trin?", options:["Budgettet iværksættes","Mål- og situationsanalyse", "Informationsmøde","Ledelsen godkender budgettet"], correct:1, explanation:"Trin 1 er mål- og situationsanalyse: strategi, styrker/svagheder, muligheder/trusler.", questionVersion:1 },
      { id:"u39-b8", goalId:"uge39-g2", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:1, tags:["bsc"], prompt:"Hvilke fire perspektiver indgår i Balanced Scorecard?", options:["Kun det økonomiske og kundeperspektivet","Økonomisk, lærings-/udviklings-, kunde- og internt procesperspektiv","Kun interne procesperspektiver","Salg, marketing, produktion og HR"], correct:1, explanation:"BSC bygges op om fire perspektiver: økonomisk, lærings- og udvikling, kunde og interne processer.", questionVersion:1 },
      { id:"u39-b9", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:1, tags:["budgetteringsforloeb"], prompt:"Hvad sker der i trin 3 (\"budgetsammenstilling\") af budgetteringsforløbet?", options:["Ledelsen godkender budgettet endeligt","Delbudgetterne fra afdelingerne samles","Budgettet kommunikeres til hele organisationen","Budgettet træder i kraft"], correct:1, explanation:"Trin 3, budgetsammenstilling, handler om at samle de delbudgetter, afdelingerne har udarbejdet i trin 2.", questionVersion:1 },
      { id:"u39-b10", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"tf", difficulty:1, tags:["budgetteringsforloeb"], prompt:"Budgetteringsforløbet er typisk en ren top-down-proces uden dialog mellem afdelingerne.", correct:false, explanation:"Processen beskrives som en dialog — internt i ledelsen, mellem ledelse og afdelinger, mellem afdelinger indbyrdes og internt i afdelingerne.", questionVersion:1 },
      { id:"u39-b11", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:1, tags:["budgetformaal"], prompt:"Hvilken af følgende er IKKE nævnt som en af budgettets opgaver?", options:["Skabe interaktion og motivation","Danne kontrolgrundlag og grundlag for kreditvurdering","Erstatte behovet for et regnskab helt","Muliggøre ansvarsdelegering"], correct:2, explanation:"Budgettets opgaver er bl.a. planlægning, ressourceoptimering, motivation, ansvarsdelegering, kontrolgrundlag og kreditvurderingsgrundlag — ikke at erstatte regnskabet.", questionVersion:1 },
      { id:"u39-b12", goalId:"uge39-g2", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"flash", difficulty:1, tags:["bsc"], prompt:"Kaplans pointe om Balanced Scorecard, i én sætning?", back:"\"Hvis noget ikke kan måles, kan det ikke ledes.\"", questionVersion:1 },
      { id:"u39-b13", goalId:"uge39-g2", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"match", difficulty:2, tags:["bsc"], prompt:"Match BSC-perspektivet med et eksempel på et Early Warning-signal.", terms:["Økonomisk perspektiv","Lærings- og udviklingsperspektiv","Kundeperspektiv","Interne procesperspektiv"], defs:["Budgetter der ikke holder, faldende overskudsgrad","Højt fravær, mange opsigelser","Faldende kundetilfredshed, stigende reklamationer","Overskredne tidsfrister, planlægningssvigt"], explanation:"Hvert perspektiv har sine egne kritiske succesfaktorer, der kan bruges som tidlige advarselssignaler.", questionVersion:1 },
    ],
    anvendelse: [
      { id:"u39-a1", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"self", difficulty:3, tags:["case"], scenario:"Du sammenligner beholdningsforskydningsmodellen og ind- og udbetalingsmodellen for et likviditetsbudget.", prompt:"Forklar hvorfor indtjeningsbidraget er startpunktet i beholdningsforskydningsmodellen, og hvordan modellen adskiller sig fra ind- og udbetalingsmodellen.", checklist:["Forklarer at indtjeningsbidraget er den sidste \"kontante\" post i resultatbudgettet (før afskrivninger)","Forklarer at beholdningsforskydningsmodellen korrigerer for ændringer i debitorer/varelager/kreditorer","Forklarer at ind- og udbetalingsmodellen i stedet registrerer betalingsstrømme direkte, uafhængigt af resultatopgørelsen"], questionVersion:1 },
      { id:"u39-a2", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:3, tags:["budgetsimulering"], scenario:"Ledelsen ønsker at teste, hvordan resultatbudgettet påvirkes, hvis salget falder 10 % og renten samtidig stiger 1 procentpoint.", prompt:"Hvilket værktøj fra budgetteringsprocessen bruges typisk til dette?", options:["Budgetkontrol","Budgetsimulering","Informationsmøde","Balanced Scorecard"], correct:1, explanation:"Budgetsimulering (12.5) tester, hvordan budgettet påvirkes af ændrede forudsætninger, og giver et mere realistisk billede af risiko og handlemuligheder.", questionVersion:1 },
      { id:"u39-a3", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"self", difficulty:3, tags:["budgetkontrol"], scenario:"Et regnskabsår er afsluttet, og det faktiske dækningsbidrag var lavere end budgetteret.", prompt:"Hvad er formålet med at opgøre denne budgetafvigelse, ud over blot at konstatere den?", checklist:["Nævner at afvigelsen = regnskab − budget","Forklarer at formålet er at forbedre den fremtidige planlægning", "Understreger at det ikke kun handler om at \"bedømme facit\" bagudrettet"], questionVersion:1 },
      { id:"u39-a4", goalId:"uge39-g2", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"self", difficulty:4, tags:["case","bsc"], scenario:"En virksomhed oplever stigende medarbejderfravær og flere opsigelser, samtidig med at kundetilfredsheden falder.", prompt:"Brug Balanced Scorecards fire perspektiver og \"Early Warning\"-tanken til at forklare, hvordan disse to signaler hænger sammen, og hvorfor de bør fanges tidligt.", checklist:["Placerer fravær/opsigelser i lærings- og udviklingsperspektivet","Placerer faldende kundetilfredshed i kundeperspektivet","Forklarer Early Warning-pointen: indikatorerne afslører problemer, før de slår igennem økonomisk"], questionVersion:1 },
      { id:"u39-a5", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:2, tags:["fejlslutning"], prompt:"Hvad er balancebudgettets primære formål?", options:["At erstatte resultatbudgettet", "At vise den forventede balance ved periodens udgang, når resultat- og likviditetsbudgettet er indarbejdet", "At beregne kun likviditetsgrader", "At fastsætte virksomhedens skat"], correct:1, explanation:"Balancebudgettet viser den forventede balance ved periodens udgang og bruges bl.a. til at vurdere udviklingen i soliditet og kapitalbinding.", questionVersion:1 },
      { id:"u39-a6", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"Anvendt regneeksempel over notens dokumenterede resultatbudget-opstilling · OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:2, tags:["resultatbudget","beregning"], scenario:"Et resultatbudget viser (illustrative tal, opstillet efter notens formelrækkefølge): omsætning 500, variable omkostninger 200, kontante kapacitetsomkostninger 150, afskrivninger 40.", prompt:"Hvad er indtjeningsbidraget?", options:["300","150","110","60"], correct:1, explanation:"Dækningsbidrag = 500 − 200 = 300. Indtjeningsbidrag = dækningsbidrag − kontante kapacitetsomkostninger = 300 − 150 = 150. Afskrivningerne trækkes først fra i NÆSTE trin (resultat før renter), ikke i indtjeningsbidraget selv.", questionVersion:1 },
      { id:"u39-a7", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"self", difficulty:3, tags:["case","modelvalg"], scenario:"En virksomhed vil vurdere, om den har likviditet nok til at honorere sine forpligtelser i det kommende kvartal, uafhængigt af resultatopgørelsens periodisering.", prompt:"Hvilken af de to likviditetsbudget-modeller ville du anbefale her, og hvorfor?", checklist:["Vælger ind- og udbetalingsmodellen","Begrunder valget med, at den opgør de faktiske ind- og udbetalinger direkte, uafhængigt af periodiseringen","Forklarer hvorfor beholdningsforskydningsmodellen (baseret på resultatopgørelsen) her ville være mindre præcis til formålet"], questionVersion:1 },
      { id:"u39-a8", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:3, tags:["fejlslutning"], scenario:"En virksomhed konstaterer en positiv budgetafvigelse på dækningsbidraget, men samtidig et merforbrug på kapacitetsomkostningerne.", prompt:"Hvad er den korrekte fremgangsmåde for at vurdere den samlede budgetafvigelse på indtjeningsbidraget?", options:["Kun se på dækningsbidragets afvigelse isoleret","Se bort fra kapacitetsomkostningerne, da de ikke er en del af indtjeningsbidraget","Sammenholde begge afvigelser, da indtjeningsbidrag = dækningsbidrag − kontante kapacitetsomkostninger","Bruge udelukkende resultatbudgettets bundlinje"], correct:2, explanation:"Fordi indtjeningsbidraget defineres som dækningsbidrag minus kontante kapacitetsomkostninger, skal begge afvigelser sammenholdes for at vurdere den samlede effekt — man kan ikke bedømme det ud fra kun den ene post.", questionVersion:1 },
      { id:"u39-a9", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"self", difficulty:4, tags:["case","fejlslutning"], scenario:"Kildens eget Nordlys A/S-eksempel indeholder en beregning, der ikke går op: et dækningsbidrag 139.000 kr. bedre end budgetteret og et merforbrug på kapacitetsomkostninger på 241.000 kr. burde isoleret set give et indtjeningsbidrag, der er 102.000 kr. dårligere end budgetteret — men kildens egen konklusion angiver et andet tal.", prompt:"Hvordan bør du forholde dig til denne type uoverensstemmelse, når du forbereder dig til eksamen?", checklist:["Genkender at 139.000 − 241.000 = −102.000, ikke det tal kilden konkluderer", "Forklarer at man ikke bør bruge det uverificerede facittal til eksamen, før det er kontrolleret mod bogens originale Nordlys-eksempel","Foreslår at bekræfte om der mangler en tredje afvigelse (fx afskrivninger, renter eller skat), som kunne forklare forskellen"], questionVersion:1 },
      { id:"u39-a10", goalId:"uge39-g2", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:2, tags:["bsc"], prompt:"Hvorfor kaldes BSC's fire perspektiver et \"Early Warning System\"?", options:["Fordi de kun bruges én gang om året","Fordi indikatorerne i hvert perspektiv kan afsløre problemer under opsejling, før de for alvor slår igennem økonomisk","Fordi de kun advarer om skatteproblemer","Fordi de erstatter budgetkontrol"], correct:1, explanation:"Perspektiverne kan bruges som Early Warning-system: fx stigende fravær eller faldende kundetilfredshed viser sig ofte, før de økonomiske konsekvenser slår fuldt igennem.", questionVersion:1 },
      { id:"u39-a11", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"self", difficulty:3, tags:["case"], scenario:"En afdelingsleder springer trin 4 (\"koordination og vurdering\") over i budgetteringsforløbet og sender sit delbudget direkte videre til godkendelse.", prompt:"Hvilket problem kan det skabe, at koordinationstrinnet springes over, når budgettet involverer flere afdelinger?", checklist:["Forklarer at trin 4 er der, hvor delbudgetterne afstemmes på tværs af afdelinger","Peger på risikoen for indbyrdes modstridende eller urealistiske forudsætninger mellem afdelinger","Kobler det til, at budgetprocessen ifølge kilden er en dialog, ikke en række isolerede skridt"], questionVersion:1 },
      { id:"u39-a12", goalId:"uge39-g1", weekId:"uge39", subjectId:"eo", source:"note", sourceLabel:"OneNote-afledt note · EØ · Budgettering (Uge 39)", type:"mc", difficulty:2, tags:["likviditetsbudget"], scenario:"En virksomhed vil vurdere, hvordan ændringer i debitorer, varelager og kreditorer påvirker likviditeten, med udgangspunkt i indtjeningsbidraget.", prompt:"Hvilken likviditetsbudget-model bygger denne fremgangsmåde på?", options:["Ind- og udbetalingsmodellen","Beholdningsforskydningsmodellen","Balanced Scorecard","Budgetsimulering"], correct:1, explanation:"Beholdningsforskydningsmodellen tager udgangspunkt i indtjeningsbidraget og korrigerer for ændringer i debitorer, varelager og kreditorer — opbygget som pengestrømsopgørelsen.", questionVersion:1 },
    ],
  },
};
